version: 2

#python:
#  version: 3.7
#  install:
#    - requirements: requirements.txt
#    - method: pip
#      path: .
#      extra_requirements:
#        - tests
#        - docs
#  system_packages: true

conda:
  environment: environment.yml
python:
  version: 3.7
