version: 2

formats:
  - none
python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - tests
        - docs
  system_packages: true
